name: DeployASCPricingUsingPowerShell

on:
  push:
    branches: 
    - none
  pull_request:
    branches: 
    - none

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: 
          Install-Module -Name "Az.Security" -Force -AllowClobber
        azPSVersion: 
          latest

    - name: Azure PowerShell Action
      shell: pwsh
      run: |
        .\PowerShell\deployToSub.ps1
