name: Deploy Defender ARM Template

on:
  push:
    branches: 
    - none
  pull_request:
    branches: 
    - none

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: 
          New-AzDeployment -Location "eastus2" -TemplateFile .\ARM-DEPLOYMENT\azuredeploy.json
          latest
        failOnStandardError: false
        githubToken: ${{ github.token }}

